In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import necessary libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

import os
import glob
import json
from pathlib import Path

# **1. Clean Data**

In [4]:
input_file_path = '/content/drive/MyDrive/Senzmate_New/RCA/sensor.csv'

output_file_path = '/content/drive/MyDrive/Senzmate_New/RCA/sensors_cleaned_data.csv'

In [25]:
main_df=pd.read_csv(input_file_path,  on_bad_lines='skip', index_col=False) #reading csv file

<ipython-input-25-58c7020f5724>:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  main_df=pd.read_csv(input_file_path,  on_bad_lines='skip', index_col=False) #reading csv file

In [26]:
main_df.head(5)

,_id,_class,deviceId,number,code,time,value,creationDate,modifiedDate,flag
0,{'$oid': '6296ac052d3b87317271645b'},com.magma.core.data.entity.Sensor,865067023399523,0,CS,{'$date': '2022-06-01T00:00:05.101Z'},0,{'$date': '2022-06-01T00:00:05.101Z'},{'$date': '2022-06-01T00:00:05.101Z'},NaN
1,{'$oid': '6296ac052d3b87317271645c'},com.magma.core.data.entity.Sensor,865067023399523,2,B,{'$date': '2022-06-01T00:00:05.101Z'},297,{'$date': '2022-06-01T00:00:05.102Z'},{'$date': '2022-06-01T00:00:05.102Z'},NaN
2,{'$oid': '6296ac0d2d3b87317271645e'},com.magma.core.data.entity.Sensor,865067027391260,0,T,{'$date': '2022-06-01T00:00:13.160Z'},26.25,{'$date': '2022-06-01T00:00:13.160Z'},{'$date': '2022-06-01T00:00:13.160Z'},NaN
3,{'$oid': '6296ac0d2d3b87317271645f'},com.magma.core.data.entity.Sensor,865067027391260,1,H,{'$date': '2022-06-01T00:00:13.160Z'},106.63,{'$date': '2022-06-01T00:00:13.161Z'},{'$date': '2022-06-01T00:00:13.161Z'},NaN
4,{'$oid': '6296ac0d2d3b873172716460'},com.magma.core.data.entity.Sensor,865067027391260,2,MEA,{'$date': '2022-06-01T00:00:13.160Z'},211.00/216.82,{'$date': '2022-06-01T00:00:13.162Z'},{'$date': '2022-06-01T00:00:13.162Z'},NaN

In [27]:
main_df = pd.DataFrame(main_df)[['deviceId', 'code', 'time', 'value']]
main_df.head(5)

          deviceId code                                   time          value
0  865067023399523   CS  {'$date': '2022-06-01T00:00:05.101Z'}              0
1  865067023399523    B  {'$date': '2022-06-01T00:00:05.101Z'}            297
2  865067027391260    T  {'$date': '2022-06-01T00:00:13.160Z'}          26.25
3  865067027391260    H  {'$date': '2022-06-01T00:00:13.160Z'}         106.63
4  865067027391260  MEA  {'$date': '2022-06-01T00:00:13.160Z'}  211.00/216.82

In [28]:
needed_sensor_data = ["B", "IT", "LIA1", "H", "IRO", "T", "ST", "SS"]

In [29]:
main_df2 = main_df.loc[main_df['code'].isin(needed_sensor_data)].reset_index(drop=True)
main_df2.head()

          deviceId code                                   time   value
0  865067023399523    B  {'$date': '2022-06-01T00:00:05.101Z'}     297
1  865067027391260    T  {'$date': '2022-06-01T00:00:13.160Z'}   26.25
2  865067027391260    H  {'$date': '2022-06-01T00:00:13.160Z'}  106.63
3  865067027391260    B  {'$date': '2022-06-01T00:00:13.160Z'}     289
4  869170033897092    T  {'$date': '2022-06-01T00:00:13.687Z'}   23.85

In [30]:
main_df2.to_csv(output_file_path, index=False)

In [31]:
new_df=pd.read_csv(output_file_path,  on_bad_lines='skip')
new_df.head(5)

          deviceId code                                   time   value
0  865067023399523    B  {'$date': '2022-06-01T00:00:05.101Z'}     297
1  865067027391260    T  {'$date': '2022-06-01T00:00:13.160Z'}   26.25
2  865067027391260    H  {'$date': '2022-06-01T00:00:13.160Z'}  106.63
3  865067027391260    B  {'$date': '2022-06-01T00:00:13.160Z'}     289
4  869170033897092    T  {'$date': '2022-06-01T00:00:13.687Z'}   23.85