In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import necessary libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

import os
import glob
import json
from pathlib import Path

# **1. Clean Data**

In [12]:
# input_file_path = '/content/drive/MyDrive/Senzmate/RCA/test_jsonoutput3.csv'
input_file_path = '/content/drive/MyDrive/Senzmate/RCA/jsonoutput3.csv'

# output_file_path = '/content/drive/MyDrive/Senzmate/RCA/results/test_jsonoutput3_cleaned_data.csv'
output_file_path = '/content/drive/MyDrive/Senzmate/RCA/results/jsonoutput3_cleaned_data.csv'

In [13]:
main_df=pd.read_csv(input_file_path,  on_bad_lines='skip', index_col=0) #reading csv file

<ipython-input-13-d7d0bf3236af>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  main_df=pd.read_csv(input_file_path,  on_bad_lines='skip', index_col=0) #reading csv file

In [14]:
main_df.head(5)

,_id,_class,deviceId,number,code,time,value,creationDate,modifiedDate
0,61cf998d2d3b872d3baa528e,com.magma.core.data.entity.Sensor,869170034808734,0,T,2022-01-01T00:00:13.521Z,21.14,2022-01-01T00:00:13.522Z,2022-01-01T00:00:13.522Z
1,61cf998d2d3b872d3baa528f,com.magma.core.data.entity.Sensor,869170034808734,1,H,2022-01-01T00:00:13.521Z,103.10,2022-01-01T00:00:13.523Z,2022-01-01T00:00:13.523Z
2,61cf998d2d3b872d3baa5290,com.magma.core.data.entity.Sensor,869170034808734,2,MEA4,2022-01-01T00:00:13.521Z,545.00/163.00,2022-01-01T00:00:13.524Z,2022-01-01T00:00:13.524Z
3,61cf998d2d3b872d3baa5291,com.magma.core.data.entity.Sensor,869170034808734,3,B,2022-01-01T00:00:13.521Z,266,2022-01-01T00:00:13.524Z,2022-01-01T00:00:13.524Z
4,61cf99902d3b872d3baa5297,com.magma.core.data.entity.Sensor,869170034809062,0,T,2022-01-01T00:00:16.445Z,13.44,2022-01-01T00:00:16.445Z,2022-01-01T00:00:16.445Z

In [15]:
main_df.drop(['_id', '_class', 'number', 'creationDate', 'modifiedDate'], axis=1, inplace=True)
main_df.head(5)

          deviceId  code                      time          value
0  869170034808734     T  2022-01-01T00:00:13.521Z          21.14
1  869170034808734     H  2022-01-01T00:00:13.521Z         103.10
2  869170034808734  MEA4  2022-01-01T00:00:13.521Z  545.00/163.00
3  869170034808734     B  2022-01-01T00:00:13.521Z            266
4  869170034809062     T  2022-01-01T00:00:16.445Z          13.44

In [11]:
first_column_label = main_df.columns[0]
main_df = main_df.drop(columns=first_column_label)
main_df.head(5)

,time,value,flag
_id,,,
{'$oid': '6296ac052d3b87317271645b'},{'$date': '2022-06-01T00:00:05.101Z'},0,NaN
{'$oid': '6296ac052d3b87317271645c'},{'$date': '2022-06-01T00:00:05.101Z'},297,NaN
{'$oid': '6296ac0d2d3b87317271645e'},{'$date': '2022-06-01T00:00:13.160Z'},26.25,NaN
{'$oid': '6296ac0d2d3b87317271645f'},{'$date': '2022-06-01T00:00:13.160Z'},106.63,NaN
{'$oid': '6296ac0d2d3b873172716460'},{'$date': '2022-06-01T00:00:13.160Z'},211.00/216.82,NaN

In [ ]:
needed_sensor_data = ["B", "IT", "LIA1", "H", "IRO", "T", "ST", "SS"]

In [ ]:
main_df2 = main_df.loc[main_df['code'].isin(needed_sensor_data)].reset_index(drop=True)
main_df2.head()

          deviceId code                      time   value
0  869170034808734    T  2022-01-01T00:00:13.521Z   21.14
1  869170034808734    H  2022-01-01T00:00:13.521Z  103.10
2  869170034808734    B  2022-01-01T00:00:13.521Z     266
3  869170034809062    T  2022-01-01T00:00:16.445Z   13.44
4  869170034809062    H  2022-01-01T00:00:16.445Z   98.55

In [ ]:
main_df2.to_csv(output_file_path, index=False)

In [ ]:
new_df=pd.read_csv(output_file_path,  on_bad_lines='skip')
new_df.head(5)

/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

          deviceId code                      time   value
0  869170034808734    T  2022-01-01T00:00:13.521Z   21.14
1  869170034808734    H  2022-01-01T00:00:13.521Z  103.10
2  869170034808734    B  2022-01-01T00:00:13.521Z     266
3  869170034809062    T  2022-01-01T00:00:16.445Z   13.44
4  869170034809062    H  2022-01-01T00:00:16.445Z   98.55