In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Import necessary libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

# **1. Import the main csv file sent by embedded team**

In [3]:
df=pd.read_csv("/content/drive/MyDrive/Senzmate/RCA/jsonoutput3.csv",  on_bad_lines='skip')#reading csv file

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.head(5)

,Unnamed: 0,_id,_class,deviceId,number,code,time,value,creationDate,modifiedDate
0,0,61cf998d2d3b872d3baa528e,com.magma.core.data.entity.Sensor,869170034808734,0,T,2022-01-01T00:00:13.521Z,21.14,2022-01-01T00:00:13.522Z,2022-01-01T00:00:13.522Z
1,1,61cf998d2d3b872d3baa528f,com.magma.core.data.entity.Sensor,869170034808734,1,H,2022-01-01T00:00:13.521Z,103.10,2022-01-01T00:00:13.523Z,2022-01-01T00:00:13.523Z
2,2,61cf998d2d3b872d3baa5290,com.magma.core.data.entity.Sensor,869170034808734,2,MEA4,2022-01-01T00:00:13.521Z,545.00/163.00,2022-01-01T00:00:13.524Z,2022-01-01T00:00:13.524Z
3,3,61cf998d2d3b872d3baa5291,com.magma.core.data.entity.Sensor,869170034808734,3,B,2022-01-01T00:00:13.521Z,266,2022-01-01T00:00:13.524Z,2022-01-01T00:00:13.524Z
4,4,61cf99902d3b872d3baa5297,com.magma.core.data.entity.Sensor,869170034809062,0,T,2022-01-01T00:00:16.445Z,13.44,2022-01-01T00:00:16.445Z,2022-01-01T00:00:16.445Z

# **2. Group the dataframe for each device**

*   "deviceId" is used to group

In [5]:
grp_deviceId = df.groupby('deviceId')

In [14]:
for id,df in grp_deviceId:
  df_columns = list(df.columns)
  print(df_columns)
  table = df.reset_index().pivot(values='value', index="time", columns='code')
  print(table)
  table.to_csv('/content/drive/MyDrive/Senzmate/RCA/Analyzed_dataframes_for_each_devices/{}.csv'.format(id))
  # break

['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H  IT     MEA4  SS       T
time
2022-06-05T11:35:16.426Z  297  -6.00  56  528/706  00  -46.85
2022-06-05T11:51:35.004Z  297  -6.00  57  528/706  00  -46.85
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B   H  IT     MEA4  ST   T
time
2022-01-29T02:46:35.413Z  287  76  53  524/711  31  27
2022-01-29T02:56:35.465Z  285  75  53  524/711  31  27
2022-01-29T03:06:35.432Z  286  73  53  526/711  31  28
2022-01-29T03:16:35.477Z  286  71  53  524/711  31  28
2022-01-29T03:26:35.473Z  282  70  53  524/711  31  28
...                       ...  ..  ..      ...  ..  ..
2022-01-29T17:36:35.797Z  283  88  53  524/711  31  28
2022-01-29T17:46:35.815Z  283  88  53  524/711  31  28
2022-01-29T17:56:35.854Z  280  88  53  524/711  31  28
2022-01-29T18:06:35.798Z  282  87  53  524/711  31  28
2022-01-29T18:16:35.797Z  283  88  53  524/711  31  28

[94 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B   H  IT     MEA4  ST   T
time
2022-01-29T02:50:34.252Z  296  75  55  527/712  31  27
2022-01-29T03:00:34.240Z  298  75  56  527/712  31  27
2022-01-29T03:10:34.151Z  301  57  58  527/712  31  32
2022-01-29T03:20:34.083Z  302  50  58  527/712  31  34
2022-01-29T03:30:34.004Z  300  49  60  527/712  31  34
...                       ...  ..  ..      ...  ..  ..
2022-01-29T17:40:28.964Z  307  88  56  527/712  31  28
2022-01-29T17:50:28.932Z  308  87  55  527/712  31  28
2022-01-29T18:00:28.834Z  307  87  56  527/712  31  28
2022-01-29T18:10:28.768Z  308  87  55  527/712  31  28
2022-01-29T18:20:28.713Z  308  88  55  527/712  31  28

[94 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B   H  IT     MEA4  ST   T
time
2022-01-29T02:44:36.199Z  295  75  55  526/713  26  27
2022-01-29T02:54:36.931Z  293  74  55  526/713  26  28
2022-01-29T03:04:37.805Z  294  58  56  526/713  26  33
2022-01-29T03:14:38.677Z  293  54  57  526/713  26  33
2022-01-29T03:24:39.395Z  294  54  57  526/713  26  33
...                       ...  ..  ..      ...  ..  ..
2022-01-29T17:37:13.199Z  288  87  55  526/713  25  28
2022-01-29T17:47:13.842Z  289  87  56  526/713  25  28
2022-01-29T17:57:14.483Z  288  88  56  526/713  25  28
2022-01-29T18:07:15.091Z  291  87  56  525/713  25  28
2022-01-29T18:17:16.015Z  289  87  56  525/713  25  27

[94 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                         B      H    IT     MEA4  SS     T
time
2022-01-27T10:20:31.413Z   312   51.4  60.2  603/380  13  31.9
2022-01-27T10:31:41.020Z  1258   51.7  59.7  598/376  12  29.6
2022-01-27T10:42:31.310Z   314   61.2  57.2  602/380  13  28.2
2022-01-27T10:52:31.254Z   312   64.0  55.9  597/376  13  26.9
2022-01-27T11:02:31.639Z   314   65.1  55.0  599/378  13  26.8
...                        ...    ...   ...      ...  ..   ...
2022-01-29T14:23:15.250Z   309  101.6  49.0  537/500  12  23.0
2022-01-29T14:33:10.195Z   309  101.8  49.8  542/498   9  23.1
2022-01-29T14:43:10.210Z   308  101.9  49.8  541/498  13  23.0
2022-01-29T15:04:40.136Z   310  102.1  48.5  539/497  11  22.9
2022-01-29T15:26:40.094Z   308  102.3  48.5  545/488   9  23.0

[118 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H    IT     MEA4  SS     T
time
2022-01-27T10:16:37.404Z  321   54.9  62.2  545/427  10  30.7
2022-01-27T10:26:35.934Z  321   55.2  61.7  548/419  10  30.9
2022-01-27T10:36:36.794Z  321   54.2  61.7  549/421   9  31.2
2022-01-27T10:59:47.433Z  321   56.0  61.3  549/424  10  30.3
2022-01-27T11:12:19.221Z  321   58.1  60.9  546/425  10  29.4
...                       ...    ...   ...      ...  ..   ...
2022-01-29T17:39:36.289Z  311  100.9  52.2  557/404   8  24.2
2022-01-29T17:49:36.870Z  311  100.8  52.2  557/402   9  24.2
2022-01-29T17:59:37.168Z  311  100.8  52.2  561/405   9  24.2
2022-01-29T18:09:37.704Z  311  100.8  51.7  555/400  10  24.1
2022-01-29T18:19:38.113Z  311  100.7  52.2  559/400   8  24.1

[243 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H    IT     MEA4 SS     T
time
2022-01-27T10:18:53.909Z  316   43.2  66.9  477/416  7  34.9
2022-01-27T10:28:53.748Z  317   39.2  68.2  474/410  7  36.5
2022-01-27T10:50:53.681Z  316   39.6  70.8  477/419  3  36.9
2022-01-27T11:00:54.889Z  317   45.0  66.5  478/414  6  32.6
2022-01-27T11:11:03.611Z  318   52.5  65.6  475/406  7  31.2
...                       ...    ...   ...      ... ..   ...
2022-01-29T17:36:58.160Z  307  102.3  54.9  474/385  6  23.4
2022-01-29T17:46:53.326Z  309  102.3  55.3  476/384  5  23.4
2022-01-29T17:58:11.957Z  307  102.3  54.9  478/382  6  23.4
2022-01-29T18:09:25.534Z  308  102.4  54.9  473/395  6  23.4
2022-01-29T18:19:25.035Z  308  102.4  54.9  474/388  6  23.4

[269 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H    IT     MEA4  SS     T
time
2022-01-27T10:30:18.168Z  308   67.1  51.5  472/158  13  26.2
2022-01-27T10:40:00.850Z  307   69.3  50.6  468/157  13  25.0
2022-01-27T14:09:57.600Z  304   76.5  43.7  468/162  16  21.2
2022-01-27T15:31:16.022Z  303   84.3  43.7  467/156  14  20.3
2022-01-27T15:42:36.140Z  303   86.2  43.3  469/158  13  20.0
...                       ...    ...   ...      ...  ..   ...
2022-01-29T17:10:09.730Z  303  102.1  44.6  468/159  14  21.5
2022-01-29T17:20:06.161Z  303  102.0  44.6  467/157  14  21.4
2022-01-29T17:50:05.348Z  303  101.9  44.2  473/160  15  20.8
2022-01-29T18:00:10.932Z  302  102.0  44.2  468/159  14  20.4
2022-01-29T18:20:18.307Z  302  102.3  43.3  467/161  13  20.1

[114 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B     H    IT     MEA4  SS     T
time
2022-01-29T10:58:25.348Z  273  75.3  59.4  458/718  10  29.5
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H    IT     MEA4  SS     T
time
2022-01-27T10:23:27.638Z  278   56.1  59.6  570/512  18  30.1
2022-01-27T10:33:32.872Z  278   58.2  59.2  565/513  20  28.6
2022-01-27T10:43:28.216Z  277   64.4  58.3  555/518  20  27.2
2022-01-27T10:53:28.647Z  277   69.0  57.0  556/520  20  26.4
2022-01-27T11:03:29.188Z  277   68.5  56.6  560/519  20  26.3
...                       ...    ...   ...      ...  ..   ...
2022-01-29T14:28:39.112Z  275  101.4  51.0  560/520  20  22.7
2022-01-29T14:38:39.584Z  275  101.5  51.0  563/515  19  22.8
2022-01-29T14:48:39.931Z  274  101.5  51.0  552/523  19  22.8
2022-01-29T14:58:40.272Z  274  101.7  51.0  553/525  20  22.7
2022-01-29T15:18:40.561Z  274  101.7  50.2  566/516  20  22.7

[127 rows x 6 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B     H    IT     MEA4  SS     T
time
2022-01-27T10:16:13.162Z  272  53.2  62.3  541/165  14  32.3
2022-01-27T10:26:13.454Z  276  50.7  62.3  541/168  10  32.5
2022-01-27T10:46:14.147Z  272  53.0  61.5  537/164  11  31.0
2022-01-28T06:06:07.326Z  272  38.8  72.7  545/162  10  42.1
2022-01-28T06:16:07.759Z  275  49.0  70.5  543/165  12  36.3
2022-01-28T06:26:08.194Z  272  40.5  72.2  546/162  10  42.1
2022-01-29T08:30:32.843Z  277  35.5  75.3  536/164  11  45.2
2022-01-29T08:40:37.963Z  271  36.9  74.0  533/167   8  45.9
2022-01-29T08:51:47.086Z  273  32.3  75.3  531/165   6  47.7
2022-01-29T09:13:04.557Z  272  31.3  76.1  531/166  10  47.3
2022-01-29T09:23:04.868Z  272  32.5  76.1  528/170  10  47.0
2022-01-29T09:33:05.429Z  277  32.9  75.3  535/171  10  46.5
2022-01-29T09:43:05.458Z  272  30.0  76.1  528/174   8  49.8
2022-01-29T09:53:08.113Z  275  30.2  76.6  527/169  11  49.7
2022-01-29T10:03:12.004Z  272  34.8  76.1  530/173  10  46.1
2022-01-29T10:13:06.548Z  272  47.0  73.1  531/168  10  39.1
2022-01-29T10:33:09.844Z  272  58.6  66.6  532/174  12  33.6
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B   CT   H   IT     MEA4  ST    T       X       Y
time
2022-01-27T10:18:46.038Z  NaN   75  -6  NaN      NaN  15   20  154834  270122
2022-01-27T10:28:45.919Z  NaN   75  -6  NaN      NaN  18   20  155834  270122
2022-01-27T10:38:45.933Z  NaN   74  -6  NaN      NaN  18   20  160834  270122
2022-01-27T10:48:45.895Z  NaN   74  -6  NaN      NaN  18   20  161834  270122
2022-01-27T10:58:45.709Z  NaN   73  -6  NaN      NaN  18   20  162834  270122
...                       ...  ...  ..  ...      ...  ..  ...     ...     ...
2022-01-28T15:17:00.000Z  100  NaN  -6   55  259/376  28  -46     NaN     NaN
2022-01-28T15:20:00.000Z  100  NaN  -6   55  260/377  28  -46     NaN     NaN
2022-01-28T15:25:27.432Z  262  NaN  -6   55  260/377  13  -46     NaN     NaN
2022-01-28T15:27:08.738Z  292  NaN  -6   57  247/356  13  -46     NaN     NaN
2022-01-28T15:30:08.714Z  297  NaN  -6   56  253/365  13  -46     NaN     NaN

[229 rows x 9 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B     H    IT    P    RF  SS     T   WD   WS
time
2022-03-22T07:48:15.095Z  285  50.0  78.3  0.0  0.00  28  35.0  0.0  4.0
2022-03-22T07:58:15.013Z  286  48.0  80.4  0.0  0.00  28  36.0  0.0  4.0
2022-03-22T08:08:14.928Z  286  50.0  80.4  0.0  0.00  28  36.0  0.0  4.0
2022-03-22T08:18:14.834Z  287  49.0  81.3  0.0  0.00  28  36.0  0.0  4.0
2022-03-22T08:40:14.937Z  288  48.0  83.0  0.0  0.00  28  37.0  0.0  4.0
...                       ...   ...   ...  ...   ...  ..   ...  ...  ...
2022-06-05T15:17:39.210Z  292  79.0  60.6  0.0  0.00  22  28.0  5.0  4.0
2022-06-05T15:27:39.297Z  292  79.0  60.6  0.0  0.00  25  28.0  5.0  4.0
2022-06-05T15:37:39.034Z  291  80.0  60.6  0.0  0.00  26  28.0  5.0  4.0
2022-06-05T15:47:38.979Z  291  80.0  61.5  0.0  0.00  27  28.0  5.0  4.0
2022-06-05T15:57:39.243Z  291  79.0  61.0  0.0  0.00  27  28.0  5.0  4.0

[491 rows x 9 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H              IRO   IT     MEA4   SS  \
time
2022-03-21T19:23:06.835Z  276  83.63  0061/4095/28.60   56  767/158   12
2022-03-21T19:33:06.753Z  276  83.83  0061/4095/28.60   56  762/165   12
2022-03-21T19:43:06.574Z  276  84.12  0061/4095/28.56   56  769/157   12
2022-03-21T19:53:06.600Z  276  84.52  0061/4095/28.50   56  769/160   11
2022-03-21T20:03:06.493Z  276  84.78  0062/4095/28.48   56  765/160   12
...                       ...    ...              ...  ...      ...  ...
2022-04-25T07:45:16.704Z  299    NaN              NaN  NaN      NaN  NaN
2022-04-25T07:54:45.615Z  299    NaN              NaN  NaN      NaN  NaN
2022-04-25T08:04:14.524Z  298    NaN              NaN  NaN      NaN  NaN
2022-04-25T08:13:44.534Z  299    NaN              NaN  NaN      NaN  NaN
2022-04-25T08:23:13.567Z  298    NaN              NaN  NaN      NaN  NaN

code                          T     X
time
2022-03-21T19:23:06.835Z  28.60  1865
2022-03-21T19:33:06.753Z  28.60  1866
2022-03-21T19:43:06.574Z  28.56  1864
2022-03-21T19:53:06.600Z  28.50  1866
2022-03-21T20:03:06.493Z  28.48  1865
...                         ...   ...
2022-04-25T07:45:16.704Z    NaN   NaN
2022-04-25T07:54:45.615Z    NaN   NaN
2022-04-25T08:04:14.524Z    NaN   NaN
2022-04-25T08:13:44.534Z    NaN   NaN
2022-04-25T08:23:13.567Z    NaN   NaN

[138 rows x 8 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H              IRO   IT     MEA4   SS  \
time
2022-03-21T19:26:49.910Z  283  83.53  0070/4095/28.77   61  292/356   17
2022-03-21T19:36:49.825Z  282  84.24  0069/4095/28.70   60  291/356   20
2022-03-21T19:46:49.874Z  282  83.76  0070/4095/28.72   61  292/355   18
2022-03-21T19:56:49.677Z  281  84.67  0070/4095/28.65   61  292/356   18
2022-03-21T20:06:49.584Z  282  84.36  0070/4095/28.61   61  291/356   19
...                       ...    ...              ...  ...      ...  ...
2022-05-31T20:50:25.918Z  234    NaN              NaN  NaN      NaN  NaN
2022-05-31T20:53:03.954Z  234    NaN              NaN  NaN      NaN  NaN
2022-05-31T20:56:14.862Z  235    NaN              NaN  NaN      NaN  NaN
2022-05-31T21:05:36.952Z  235    NaN              NaN  NaN      NaN  NaN
2022-05-31T21:05:49.218Z  235    NaN              NaN  NaN      NaN  NaN

code                          T     X
time
2022-03-21T19:26:49.910Z  28.77  1864
2022-03-21T19:36:49.825Z  28.70  1864
2022-03-21T19:46:49.874Z  28.72  1864
2022-03-21T19:56:49.677Z  28.65  1864
2022-03-21T20:06:49.584Z  28.61  1864
...                         ...   ...
2022-05-31T20:50:25.918Z    NaN   NaN
2022-05-31T20:53:03.954Z    NaN   NaN
2022-05-31T20:56:14.862Z    NaN   NaN
2022-05-31T21:05:36.952Z    NaN   NaN
2022-05-31T21:05:49.218Z    NaN   NaN

[693 rows x 8 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H               IRO  IT     MEA4  SS  \
time
2022-03-21T19:22:23.798Z  310  79.94   3014/1869/29.21  56  561/416  19
2022-03-21T19:32:23.732Z  310  80.19   3010/1872/29.18  55  562/413  18
2022-03-21T19:42:23.559Z  310  81.12   3009/1866/29.09  56  557/411  18
2022-03-21T19:52:00.000Z  310  80.87   3001/1874/29.06  56  558/410  00
2022-03-21T20:02:41.796Z  310  81.31   3001/1874/29.00  55  557/414  18
...                       ...    ...               ...  ..      ...  ..
2022-04-25T07:34:54.176Z  317  -6.00  3632/1193/-46.85  67  757/424  26
2022-04-25T07:44:54.201Z  319  -6.00  3579/1249/-46.85  67  750/408  26
2022-04-25T07:54:54.137Z  319  -6.00  3527/1273/-46.85  68  752/414  28
2022-04-25T08:04:54.028Z  318  -6.00  3460/1323/-46.85  70  751/407  27
2022-04-25T08:14:54.009Z  319  -6.00  3412/1385/-46.85  67  747/412  28

code                           T     X
time
2022-03-21T19:22:23.798Z   29.21  1852
2022-03-21T19:32:23.732Z   29.18  1851
2022-03-21T19:42:23.559Z   29.09  1852
2022-03-21T19:52:00.000Z   29.06   NaN
2022-03-21T20:02:41.796Z   29.00  1850
...                          ...   ...
2022-04-25T07:34:54.176Z  -46.85  1850
2022-04-25T07:44:54.201Z  -46.85  1851
2022-04-25T07:54:54.137Z  -46.85  1850
2022-04-25T08:04:54.028Z  -46.85  1851
2022-04-25T08:14:54.009Z  -46.85  1851

[574 rows x 8 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H              IRO  IT    LIA1     MEA4  \
time
2022-03-21T19:16:00.000Z  313  82.81  0374/3914/28.83  56     NaN  587/170
2022-03-21T19:26:55.526Z  313  83.19  0374/3914/28.85  56     NaN  588/166
2022-03-21T19:36:37.225Z  313  83.73  0372/3921/28.82  55     NaN  585/169
2022-03-21T19:46:37.152Z  313  83.68  0387/3925/28.82  56     NaN  592/170
2022-03-21T19:56:37.078Z  312  84.21  0384/3906/28.75  56     NaN  589/172
...                       ...    ...              ...  ..     ...      ...
2022-06-05T15:12:11.754Z  314  82.99              NaN  51  000000  681/197
2022-06-05T15:22:11.691Z  314  83.36              NaN  51  000000  672/189
2022-06-05T15:32:11.585Z  314  83.57              NaN  51  000000  682/198
2022-06-05T15:42:11.498Z  314  84.17              NaN  50  000000  675/195
2022-06-05T15:52:11.512Z  314  83.02              NaN  51  000000  680/198

code                      SS      T     X
time
2022-03-21T19:16:00.000Z  00  28.83   NaN
2022-03-21T19:26:55.526Z  15  28.85  1856
2022-03-21T19:36:37.225Z  15  28.82  1854
2022-03-21T19:46:37.152Z  17  28.82  1854
2022-03-21T19:56:37.078Z  16  28.75  1854
...                       ..    ...   ...
2022-06-05T15:12:11.754Z  23  28.64   NaN
2022-06-05T15:22:11.691Z  23  28.62   NaN
2022-06-05T15:32:11.585Z  22  28.56   NaN
2022-06-05T15:42:11.498Z  23  28.53   NaN
2022-06-05T15:52:11.512Z  23  28.57   NaN

[2963 rows x 9 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H              IRO   IT    LIA1     MEA4  \
time
2022-03-21T19:18:14.403Z  NaN    NaN              NaN  NaN     NaN      NaN
2022-03-21T19:28:14.165Z  311  83.36  0779/2019/28.69   55     NaN  568/169
2022-03-21T19:38:14.052Z  311  84.77  0782/2010/28.64   55     NaN  572/164
2022-03-21T19:48:13.909Z  310  84.11  0769/2009/28.61   54     NaN  569/162
2022-03-21T19:58:13.944Z  311  83.82  0786/2017/28.55   55     NaN  568/161
...                       ...    ...              ...  ...     ...      ...
2022-06-05T15:13:01.433Z  313  86.78              NaN   53  000000  692/157
2022-06-05T15:23:01.332Z  313  87.03              NaN   53  000000  692/160
2022-06-05T15:33:01.143Z  313  87.19              NaN   53  000000  695/165
2022-06-05T15:43:01.224Z  313  87.95              NaN   53  000000  694/163
2022-06-05T15:53:05.026Z  313  87.05              NaN   53  000000  694/163

code                      SS      T     X
time
2022-03-21T19:18:14.403Z  19    NaN  1862
2022-03-21T19:28:14.165Z  20  28.69  1862
2022-03-21T19:38:14.052Z  19  28.64  1862
2022-03-21T19:48:13.909Z  20  28.61  1862
2022-03-21T19:58:13.944Z  20  28.55  1862
...                       ..    ...   ...
2022-06-05T15:13:01.433Z  24  28.45   NaN
2022-06-05T15:23:01.332Z  23  28.43   NaN
2022-06-05T15:33:01.143Z  24  28.39   NaN
2022-06-05T15:43:01.224Z  24  28.37   NaN
2022-06-05T15:53:05.026Z  21  28.39   NaN

[2244 rows x 9 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H              IRO  IT  SS      T     X
time
2022-05-14T05:13:32.664Z  290  73.64  2588/2077/31.30  66  24  31.30  1864
2022-05-14T05:23:32.768Z  290  80.32  2532/2120/29.34  64  25  29.34  1864
2022-05-14T05:33:32.591Z  292  73.53  2547/2108/30.41  64  25  30.41  1864
2022-05-14T05:43:48.742Z  292  69.21  2573/2075/32.05  65  25  32.05  1864
2022-05-14T05:53:48.654Z  293  71.06  2583/2078/31.73  66  23  31.73  1864
...                       ...    ...              ...  ..  ..    ...   ...
2022-06-05T15:14:43.791Z  318  88.28  3012/1716/28.48  61  23  28.48  1864
2022-06-05T15:24:39.624Z  318  88.51  3008/1711/28.43  61  26  28.43  1864
2022-06-05T15:34:39.604Z  318  88.59  3009/1716/28.41  61  25  28.41  1864
2022-06-05T15:44:39.543Z  318  88.43  3008/1714/28.32  61  24  28.32  1864
2022-06-05T15:54:39.385Z  318  88.85  3012/1717/28.43  61  25  28.43  1864

[2583 rows x 7 columns]
['Unnamed: 0', '_id', '_class', 'deviceId', 'number', 'code', 'time', 'value', 'creationDate', 'modifiedDate']
code                        B      H               IRO  IT     MEA4  SS  \
time
2022-03-20T17:18:00.000Z  269  -6.00  0067/4095/-46.85  59  278/357  00
2022-03-20T17:28:00.000Z  269  -6.00  0067/4095/-46.85  59  278/361  00
2022-03-20T17:38:00.000Z  269  -6.00  0067/4095/-46.85  59  278/363  00
2022-03-20T17:48:00.000Z  269  -6.00  0067/4095/-46.85  59  278/363  00
2022-03-20T17:58:00.000Z  269  -6.00  0067/4095/-46.85  59  279/364  00
...                       ...    ...               ...  ..      ...  ..
2022-04-25T07:34:24.572Z  320  -6.00  0068/4095/-46.85  68  252/374  24

ValueError: ignored